### ISSUE TITLE
this.Close() will cause Call from invalid thread when closing the window

### ISSUE THREAD

**Issue by RickyYCheng** [donandren/vlcsharpavalonia#12]
According to the demand, I need to play video when the app start up.  
I use libvlcsharp to open a new view(window, i found that the usercontrol cannot play video inside the view) to display the video then close this window( if there's a better way please tell me, thanks)
My playvideoview only has one control that is the videoview, and the C# code like this:
```C#
public class PlayVideoView : Window
    {
        VideoView videoView;
        private LibVLC _libVLC;
        public PlayVideoView()
        {
            InitializeComponent();
            _libVLC = new LibVLC();
            videoView = this.Get<VideoView>("playVideoView");
            videoView.MediaPlayer = new MediaPlayer(_libVLC);


#if DEBUG
            this.AttachDevTools();
#endif
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }

        private void OnOpened(object sender, EventArgs e)
        {
            if (!videoView.MediaPlayer!.IsPlaying)
            {
                //videoView.MediaPlayer.Play(new Media(_libVLC, @"C:\Users\Ricky\Videos\Captures\2.mp4"));
            }
            videoView.MediaPlayer.EndReached += MediaPlayer_EndReached;
        }

        private void MediaPlayer_EndReached(object? sender, EventArgs e)
        {
            // call from invalid thread
            this.Close();
        }
        private void OnClosed(object sender, EventArgs e)
        {
            try
            {
                _libVLC.Dispose();
                videoView.MediaPlayer!.Media!.Dispose();
                videoView.MediaPlayer!.Dispose();
            }
            catch { }
        }
    }
```
Unfortunately, when i tried to use the endreached event to close this window, it just shows " call from invalid thread" instead of shut down the window.  
BTW, the Environment.Exit(0) works, but it will close the mainView at the same time, that's what i dont want to do.

**Comment by maxkatz6** [comment]
Use Dispather.InvokeAsync.
MediaPlayer handlers are expected (at least for me from my experience with another players like UWP one) to be called not on UI thread, so you need to synchronize it manually.

**Comment by RickyYCheng** [comment]
> Use Dispather.InvokeAsync.
> MediaPlayer handlers are expected (at least for me from my experience with another players like UWP one) to be called not on UI thread, so you need to synchronize it manually.

Thanks for your answer!  
And can you please make a short example?  I cannot understand how to use it.
I'm not a software dev but a engineer student and this app is to just make a simple industrial user interface so im not in major...

**Comment by RickyYCheng** [comment]
> > Use Dispather.InvokeAsync.
> > MediaPlayer handlers are expected (at least for me from my experience with another players like UWP one) to be called not on UI thread, so you need to synchronize it manually.
> 
> Thanks for your answer!
> And can you please make a short example? I cannot understand how to use it.
> I'm not a software dev but a engineer student and this app is to just make a simple industrial user interface so im not in major...

```C#
private void MediaPlayer_EndReached(object? sender, EventArgs e)
        {
            Action action = new Action(Close);
            Dispatcher dispatcher = new Dispatcher(/*IPlatformThreadingInterface*/);
            dispatcher.InvokeAsync(action, DispatcherPriority.Normal);
        }
```
I do not know how to deal with IPlatformThreadingInterface, and doubt whether if it's the right way to use it...

**Comment by maxkatz6** [comment]
Use static Dispatcher.UIThread.InvokeAsync

**Comment by RickyYCheng** [comment]
> Use static Dispatcher.UIThread.InvokeAsync

That works, thank you. But the Program.cs will throw a exception: 
```C#
public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);
``` 
`Attempted to read or write protected memory. This is often an indication that other memory is corrupt`
What i did is:
```C#
        private void MediaPlayer_EndReached(object? sender, EventArgs e)
        {
            Dispatcher.UIThread.InvokeAsync(Close, DispatcherPriority.Normal);
        }
```

**Comment by maxkatz6** [comment]
@RickyYChan if you are sure that error comes during Close call somewhere from Avalonia (you haven't sent any stacktraces), then you should create issue in Avalonia repository or find something related. Preferably with minimal project to reproduce the problem.

**Comment by RickyYCheng** [comment]
> @RickyYChan if you are sure that error comes during Close call somewhere from Avalonia (you haven't sent any stacktraces), then you should create issue in Avalonia repository or find something related. Preferably with minimal project to reproduce the problem.

Thank you. I'will check it later. Very appreciate! :)

**Comment by RickyYCheng** [comment]
The problem is OnClosed
if you dont dispose and every thing will be ok!
```C#
private void OnClosed(object sender, EventArgs e)
        {
            try
            {
                //_libVLC.Dispose();
                //videoView.MediaPlayer!.Media!.Dispose();
                //videoView.MediaPlayer!.Dispose();
            }
            catch { }
        }
```

**Comment by RickyYCheng** [comment]
```C#
private void OnClosed(object sender, EventArgs e) => _libVLC.Dispose();
```
