### ISSUE TITLE
If you continue to play the next video after the playback end event, will an error occur?

### ISSUE THREAD

**Issue by bbhxwl** [donandren/vlcsharpavalonia#16]
If you continue to play the next video after the playback end event, will an error occur?

This project, play VLC video. Why can't I play it continuously? I distinguish between endreached event and mediaplayer in playing video_ The stopped event attempts to replay. But after the program is executed, it will wait indefinitely.

I initialize to play the video twice in a row. There is no problem, but after playing, play the next video. It will wait indefinitely and will not be played.

![image](https://user-images.githubusercontent.com/26525599/128867735-dc072710-8400-4e26-a081-b2e0a56b70f0.png)

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/128868718-de303011-b006-4a7b-b703-8df446b90fc2.png)
If you execute any mediaplayer operation in the event, you will wait indefinitely for it to get stuck.

**Comment by 07artem132** [comment]
You shouldn't call this action from events, call this event from another thread.

**Comment by bbhxwl** [comment]
> You shouldn't call this action from events, call this event from another thread.
thank you very much. I know why, but he is not abnormal, which makes me think for a long time. Show the video, why there is a black border.


![image](https://user-images.githubusercontent.com/26525599/128974937-66f9ffdb-f899-420e-a3ba-8143fe83e20c.png)

**Comment by bbhxwl** [comment]
Is there any way to disable VLC output?
