### ISSUE TITLE
libvlcsharp support

### ISSUE THREAD

**Issue by mfkl** [donandren/vlcsharpavalonia#3]
Hi there,

We're interested in supporting avalonia in libvlcsharp. Would you like to help contribute on this? The task would be mainly
- integrate your changes into the libvlcsharp repo,
- refactor the libvlc/avalonia view interop. By using the libvlc 3 callbacks API, there is no hardware acceleration, more recent APIs in avalonia allow grabbing the native window handle, which would be enough get GPU support and remove parts of the code. 
There is a GPU accelerated callbacks API in libvlc 4, but that'd be another task altogether :)
- package and ship!

our ticket is here https://code.videolan.org/videolan/LibVLCSharp/-/issues/7. If grabbing the native window handle on mac/linux/windows is easy with avalonia, the rest is really trivial.

Feel free to close this ticket whether you're interested or not in helping :)

Cheers!

**Comment by donandren** [comment]
yes we can do that.
I've quickly added support for default rendering to native handle and it's working good, recent avalonia changes made it easy to embed child native control with handle.
so now there are 2 options for rendering handled by vlc or handled by avalonia, and this is configurable.
This is a project i've made quickly purely for fun, but in general it's working good and can be used by other people.
we need to sync if you want changes be 'official' in libvlcsharp it's gonna be fun.
Feel free to reach me to email or gitter/discord etc. same nickname.

Cheers

**Comment by mfkl** [comment]
Cool! Closing this then.

**Comment by mfkl** [comment]
FYI https://www.nuget.org/packages/LibVLCSharp.Avalonia/3.4.9-alpha01

**Comment by mfkl** [comment]
Actually if you have any hint for supporting controls over the video in avalonia, we're interested :-) https://code.videolan.org/videolan/LibVLCSharp/-/issues/408

We'll likely do like we did for WPF, unless you have another better idea https://code.videolan.org/videolan/LibVLCSharp/-/blob/3.x/src/LibVLCSharp.WPF/ForegroundWindow.cs
