### ISSUE TITLE
Avalonia 0.10.0-preview6 Video opens in a external window, not in VideoView.

### ISSUE THREAD

**Issue by bsglinux16** [donandren/vlcsharpavalonia#4]
Hello Avalonia 0.10.0-preview6 Version, installed Libvlcsharp and libvlcsharp.avalonia packages and created a video player. However, when Video Starts, Video opens in an external window, not in Videoview.
In the example Everything is Normal. But it doesn't work normally in my own project.
I tried everything but couldn't figure it out.

Versions:
Avalonia / Avalonia.Desktop = 0.10-preview6
LibVlcSharp = v3.4.8
LibVLC.windows = v3.0.11

![image](https://user-images.githubusercontent.com/35398147/98028265-ee40ac00-1e1e-11eb-86fb-08b4aaf0dcfc.png)

**Comment by donandren** [comment]
It look like initialization of `VideoView ` is not ready when play is called. You need to start first video play after VideoView is initialized e.g. after  Template is applied.

**Comment by bsglinux16** [comment]
> It look like initialization of `VideoView ` is not ready when play is called. You need to start first video play after VideoView is initialized e.g. after Template is applied.

Template ?

**Comment by bsglinux16** [comment]
Oh Sorry added videoview style app.xaml fixed thanks
