### ISSUE TITLE
.net 5.0 version ?

### ISSUE THREAD

**Issue by fforjan** [donandren/vlcsharpavalonia#5]
First, thanks !

I'm having a bit for fun learning AVALONIA  for my thanksgiving week-end  :)
I was trying to use your control but initialy with a .net 5.0 application and it didn't work.

I've returned to your sample app and although it was initially working, if I switched it to use net5.0 framework, i'm getting 

$ dotnet run -p ./samples/LibVLCSharp.Avalonia.Sample/
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reactive.ReflectionUtils.GetEventMethods[TSender,TEventArgs](Type targetType, Object target, String eventName, MethodInfo& addMethod, MethodInfo& removeMethod, Type& delegateType, Boolean& isWinRT)

I found that issue : AvaloniaUI/Avalonia#946 but not sure what to do about it.

Any idea ?

**Comment by donandren** [comment]
Look like some reactive problem - update Reactive to version 5 should fix it, checkout details
https://github.com/AvaloniaUI/Avalonia/issues/5117#issuecomment-735309025
