### ISSUE TITLE
 not visible by default then visible means issue with play/stop control (VideoView children)

### ISSUE THREAD

**Issue by fforjan** [donandren/vlcsharpavalonia#7]
So in my application, the user control which embed the view is not visible by default till the user selects a video.
When the user selects a video, i'm then getting this :
![image](https://user-images.githubusercontent.com/601810/101270026-b1234e80-3729-11eb-8865-993a0d19737e.png)
As soon as I resize, the controls are positioned properly:
![image](https://user-images.githubusercontent.com/601810/101270032-c39d8800-3729-11eb-89d6-7a7765ae2044.png)

**Comment by fforjan** [comment]
note: if I switch to   _UseVLCSharp(renderingOptions: LibVLCAvaloniaRenderingOptions.AvaloniaCustomDrawingOperation)_ then the rendering is done properly

**Comment by fforjan** [comment]
note2: if I switch the IsVisible property on the VideoView element itself and not any ancestor - in my case the VideoView is embedded into a user control into a different parent into a window, then it is behaving properly

**Comment by donandren** [comment]
should be fixed
