### ISSUE TITLE
when using default option, VideoView children buttons are not clipped properly

### ISSUE THREAD

**Issue by fforjan** [donandren/vlcsharpavalonia#8]
When I reduce the size of my window which contains a custom user control which contains the VideoView element, the play/stop button are not getting clipped properly:
![image](https://user-images.githubusercontent.com/601810/101270233-019bab80-372c-11eb-9d90-8772bd13806d.png)

**Comment by fforjan** [comment]
see #9, same fix ?
![image](https://user-images.githubusercontent.com/601810/101306693-66253c00-37fa-11eb-8778-9707afc31714.png)

**Comment by donandren** [comment]
> 
> 
> see #9, same fix ?
> ![image](https://user-images.githubusercontent.com/601810/101306693-66253c00-37fa-11eb-8778-9707afc31714.png)
this is not exactly a fix, but will make  play button be below video, when native vlc rendering is used which will be probably undesired as a final result

**Comment by fforjan** [comment]
~~what do you mean by below ? in term of z-order ?
It is working fine on my Mac and I think I check on Windows OS and it was working fine ?~~

you're right, the z-order in invalid
