### ISSUE TITLE
children of videoview do not follow visibility of ancestor

### ISSUE THREAD

**Issue by fforjan** [donandren/vlcsharpavalonia#9]
In my application, if the video I want to view is corrupted, the control which embed the VideoView is hidden.
The VLC control seems to be hidden by itself, But the control are still visible:

![image](https://user-images.githubusercontent.com/601810/101300472-91a02a80-37ea-11eb-8a47-d04f2970f21d.png)

You can still 'interact' with them but their position is now 'fixed'
![image](https://user-images.githubusercontent.com/601810/101300546-cca25e00-37ea-11eb-8409-ec87aa32a9b2.png)

**Comment by fforjan** [comment]
It seems if I do that :
![image](https://user-images.githubusercontent.com/601810/101306601-337b4380-37fa-11eb-9ac9-22236a4ca190.png)
then it is working correctly ?

**Comment by donandren** [comment]
should be fixed
